python_base:
  build: .
  volumes:
    - .:/app
  environment:
    - DATABASE_URL=postgres://postgres@db/postgres
    - REDIS_URL=redis://redis:6379
    - PYTHONDONTWRITEBYTECODE=1
    - DEBUG=True
    - ALLOWED_HOSTS=localhost,127.0.0.1,
    - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
